### PR TITLE
#644 fixed notifications permissions switch and permissions page refactor

### LINKED ISSUE #618: Detailed analyse: Handle notifiications on FE + BE

### PR DESCRIPTION
**Pull request by PavelFilo**
- permissions.tsx route rework to devide location and network permissions, 
- mutation removal from useNotificationPermission function to not happen in settings but only in permissions and login (if permissions are enabled)
closes #618

### CODE REVIEW

File: components/special/permissions/NotificationPermissions.tsx [hunk 1]
```diff
@@ -0,0 +1,45 @@
...
+    mutationFn: (body: SaveUserSettingsDto) => clientApi.usersControllerSaveUserSettings(body),
+  })
+
+  useEffect(() => {
+    if (notificationPermissionStatus !== UnifiedPermissionStatus.UNDETERMINED) {
+      onContinue()
+    }
+  }, [onContinue, notificationPermissionStatus])
+
+  const onPress = async () => {
```
Comment (radoslavzeman) [inline components/special/permissions/NotificationPermissions.tsx:29]: `handlePress`

**Review by radoslavzeman — APPROVED** [review]
very nice 🙌
