### PR TITLE
#601 Use SectionList in Vehicles screen to fix collapsed text

### LINKED ISSUE #601: Zoznam vozdiel: nevidno polku EČV a názvu vozidla
Links to bratislava/paas-mpa-private#6

Image

### PR DESCRIPTION
**Pull request by radoslavzeman**
- use SectionList instead of custom layout
  - closes #601 
  - closes bratislava/paas-mpa-private#6
- improve styles also in SectionList in map filters

### CODE REVIEW

File: app/(app)/vehicles/index.tsx [hunk 1]
```diff
@@ -110,32 +123,27 @@ const VehiclesScreen = () => {
...
+                <Typography variant="default-bold">{section.title}</Typography>
+              </View>
+            ) : null
+          }
+          className="p-5"
+          renderItem={({ item }) => (
+            <VehicleRow vehicle={item} onContextMenuPress={() => handleContextMenuPress(item.id)} />
+          )}
+          ItemSeparatorComponent={() => <Divider dividerClassname="bg-transparent h-1" />}
+          // SectionSeparatorComponent is added above and below section header, so we add only h-1 height and use workaround with top margin in renderSectionHeader
```
Comment (PavelFilo) [inline app/(app)/vehicles/index.tsx:143]: by using this approach I assume we cannot use it directly on section header, right?

**Review by PavelFilo — APPROVED** [review]
