### PR TITLE
#2, #556, #566: Fix add/delete parking cards, safe area padding, field label

### LINKED ISSUE #565: Broken safe-area when first email is added
This happens only when first email is added, only on first render.

Image

### PR DESCRIPTION
**Pull request by radoslavzeman**
See commits

- resolves bratislava/paas-mpa-private#2
  - please see and test the use-cases mentioned in the issue
- resolves #565 #566 

(I'm also testing how we can reference private issues from other repo, therefore #2, but I see that in commits, it obviously links to PRs/issues in this repo)

### CODE REVIEW

File: app/_layout.tsx [hunk 1]
```diff
@@ -67,7 +67,7 @@ const RootLayout = () => {
 
   useEffect(() => {
     if (environment.deployment === 'production') {
-      onFetchUpdateAsync()
```
Comment (PavelFilo) [inline app/_layout.tsx:70]: this is how they name it in documentation

**Review by PavelFilo — APPROVED** [review]
GJ
